# ===============================
# DATABASE (LOCAL - SQLITE)
# ===============================
spring.datasource.url=jdbc:sqlite:C:/Users/anaab/IdeaProjects/panelsv-backend/panelsv.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# UPLOADS (LOCAL)
# ===============================
app.upload-dir=C:/Users/anaab/IdeaProjects/uploads

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===============================
# CLOUDINARY (LOCAL)
# ===============================
cloudinary.cloud-name=delppu72i
cloudinary.api-key=-586863547613843
cloudinary.api-secret=Bp9WVFJjj8gns6hhp3CyZOJjX0